apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-back-sopes2g26
  labels:
    app.kubernetes.io/name: load-balancer-back-sopes2g26
spec:
  replicas: 3
  selector:
    matchLabels:
        app.kubernetes.io/name: load-balancer-back-sopes2g26
  template:
    metadata:
      labels:
          app.kubernetes.io/name: load-balancer-back-sopes2g26
    spec:
      containers:
      - image: selvinlp/practica_backso2g26:latest
        name: backbalancer
        ports:
        - containerPort: 3000